# Project information
site_name: "RTEU CEN206 Object-Oriented Programming Course"
docs_dir: docs  # Where to find the English markdown files
site_dir: site  # Where to put the English HTML files
site_author: 'Asst. Prof. Dr. Uğur CORUH'
site_url: 'https://ucoruh.github.io/ce204-object-oriented-programming/'
site_description: 'Course Notes for Object-Oriented Programming'

site_description_en: >-
    Course Notes for Software Developers

site_description_tr: >-
    Course Notes for Software Developers

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ucoruh/ce204-object-oriented-programming'
edit_uri: 'https://github.com/ucoruh/ce204-object-oriented-programming/edit/main/docs/'

# Copyright
copyright: Copyright &copy; 2019 - 2025 Asst. Prof. Dr. Uğur CORUH

#theme:
#    name: material
#   logo: assets/images/favicon.png
#   favicon: images/favicon.png
#   palette:
#       primary: teal
#       accent: pink
#   language: en
#   feature:
#       tabs: true
#   font:
#       text: Roboto
        
# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  #name: null
  #custom_dir: !ENV [THEME_DIR, "material"]
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Static files
  static_templates:
    - 404.html
    
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    
  palette:
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
#  palette:
#   - media: "(prefers-color-scheme: light)"
#     scheme: default
#     toggle:
#       icon: material/toggle-switch-off-outline
#       name: Switch to dark mode
#   - media: "(prefers-color-scheme: dark)"
#     scheme: slate
#     toggle:
#       icon: material/toggle-switch
#       name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: logo  # Adjust the file name if necessary
    
# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: GOOGLE_ANALYTICS_RTEU_CE204
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ucoruh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ugurcoruh/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ucoruh/
    - icon: fontawesome/regular/id-card
      link: https://dblp.org/pid/230/0394.html
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/my-orcid?orcid=0000-0003-4193-8401
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=KIU4ltMAAAAJ&hl=tr
    - icon: fontawesome/regular/moon
      link: https://publons.com/researcher/1540204/ugur-coruh/
    - icon: fontawesome/regular/clipboard
      link: https://avesis.erdogan.edu.tr/ugur.coruh
    - icon: material/account-circle
      link: https://www.ugurcoruh.com/
      
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ucoruh
      repo: ce204-object-oriented-programming
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite:
      guess_lang: true

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_env: "hooks:on_env"
  - external-markdown
  - mkdocs-video
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      languages:
        - locale: en
          name: "English"
          build: true
          default: true
          site_name: "RTEU CEN206 Object-Oriented Programming Course"
          nav_translations:
            "Anasayfa": "Home"
            "Ders Programı": "Syllabus"
            "Ders Modülleri": "Course Modules"
            "Lisans": "License"
            "Özgeçmiş": "Resume"
            "Revizyonlar": "Changelog"
            "Hafta-1 (Software Engineering ve OOP Java -I)": "Week-1 (Software Engineering and OOP with Java -I)"
            "Hafta-2 (OOP Java -II)": "Week-2 (OOP with Java -II)"
            "Hafta-3 (OOP Java -III)": "Week-3 (OOP with Java Part-III)"
            "Hafta-4 (UML)": "Week-4 (UML)"
            "Hafta-5 (Plantuml)": "Week-5 (Plantuml)"
            "Hafta-6 (UMPLE-I)": "Week-6 (UMPLE-I)"
            "Hafta-7 (UMPLE-II)": "Week-7 (UMPLE-II)"
            "Hafta-8 (Ara Sınav)": "Week-8 (Midterm)"
            "Hafta-9 (Tasarım Kalıpları Kullanımı)": "Week-9 (Using Design Patterns)"
            "Hafta-10 (Tasarım Kalıpları Kullanımı)": "Week-10 (Using Design Patterns)"
            "Hafta-11 (UML + UMPLE + Java Uygulamaları)": "Week-11 (UML + UMPLE + Java Implementations)"
            "Hafta-12 (SMC Uzak Servis Örnek Çalışması -I)": "Week-12 (SMC Remote Service Case Study Part-I)"
            "Hafta-13 (SMC Uzak Servis Örnek Çalışması -II)": "Week-13 (SMC Remote Service Case Study Part-II)"
            "Hafta-14 (OOP ATM Örnek Çalışması -I)": "Week-14 (OOP ATM Case Study Part-I)"
            "Hafta-15 (OOP ATM Örnek Çalışması -II)": "Week-15 (OOP ATM Case Study Part-II)"
            "Hafta-16 (Final)": "Week-16 (Final)"
            "Proje Rehberi" : "Project Guide"
        - locale: tr
          name: "Türkçe"
          build: true
          site_name: "RTEÜ CEN206 Nesne Yönelimli Programlama Kursu"
          nav_translations:
            "Home": "Anasayfa"
            "Syllabus": "Ders Programı"
            "Course Modules": "Ders Modülleri"
            "License": "Lisans"
            "Resume": "Özgeçmiş"
            "Changelog": "Revizyonlar"
            "Week-1 (Software Engineering and OOP with Java -I)": "Hafta-1 (Software Engineering ve OOP Java -I)"
            "Week-2 (OOP with Java -II)": "Hafta-2 (OOP Java -II)"
            "Week-3 (OOP with Java Part-III)": "Hafta-3 (OOP Java -III)"
            "Week-4 (UML)": "Hafta-4 (UML)"
            "Week-5 (Plantuml)": "Hafta-5 (Plantuml)"
            "Week-6 (UMPLE-I)": "Hafta-6 (UMPLE-I)"
            "Week-7 (UMPLE-II)": "Hafta-7 (UMPLE-II)"
            "Week-8 (Midterm)": "Hafta-8 (Ara Sınav)"
            "Week-9 (Using Design Patterns)": "Hafta-9 (Tasarım Kalıpları Kullanımı)"
            "Week-10 (Using Design Patterns)": "Hafta-10 (Tasarım Kalıpları Kullanımı)"
            "Week-11 (UML + UMPLE + Java Implementations)": "Hafta-11 (UML + UMPLE + Java Uygulamaları)"
            "Week-12 (SMC Remote Service Case Study Part-I)": "Hafta-12 (SMC Uzak Servis Örnek Çalışması -I)"
            "Week-13 (SMC Remote Service Case Study Part-II)": "Hafta-13 (SMC Uzak Servis Örnek Çalışması -II)"
            "Week-14 (OOP ATM Case Study Part-I)": "Hafta-14 (OOP ATM Örnek Çalışması -I)"
            "Week-15 (OOP ATM Case Study Part-II)": "Hafta-15 (OOP ATM Örnek Çalışması -II)"
            "Week-16 (Final)": "Hafta-16 (Final)"
            "Project Guide" : "Proje Rehberi"
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago
  - git-authors:
      sort_authors_by: contribution
  - git-committers:
      repository: ucoruh/ce204-object-oriented-programming
      docs_path: docs/
      branch: main
      token: ${MKDOCS_GIT_COMMITTERS_APIKEY}
  - macros

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
# Page tree
nav:
  - Home: index.md
  - Syllabus: syllabus/syllabus.md
  - Course Modules:
    - Week-1 (Software Engineering and OOP with Java -I): week-1/ce204-week-1.md
    - Week-2 (OOP with Java -II): week-2/ce204-week-2.md
    - Week-3 (OOP with Java Part-III): week-3/ce204-week-3.md
    - Week-4 (UML): week-4/ce204-week-4.md
    - Week-5 (Plantuml): week-5/ce204-week-5.md
    - Week-6 (UMPLE-I): week-6/ce204-week-6.md
    - Week-7 (UMPLE-II): week-7/ce204-week-7.md
    - Week-8 (Midterm): week-8/ce204-week-8-midterm.md
    - Week-9 (Using Design Patterns): week-9/ce204-week-9.md
    - Week-10 (Using Design Patterns): week-10/ce204-week-10.md 
    - Week-11 (UML + UMPLE + Java Implementations): week-11/ce204-week-11.md 
    - Week-12 (SMC Remote Service Case Study Part-I): week-12/ce204-week-12.md
    - Week-13 (SMC Remote Service Case Study Part-II): week-13/ce204-week-13.md
    - Week-14 (OOP ATM Case Study Part-I): week-14/ce204-week-14.md
    - Week-15 (OOP ATM Case Study Part-II): week-15/ce204-week-15.md
    - Week-16 (Final): week-16/ce204-week-16-final.md
  - Project Guide: project-guide/index.md
  - License: license.md
  - Resume: resume/index.md
  - Changelog: changelog/index.md
